### ISSUE TITLE
Read Imported data

### ISSUE THREAD

**Issue by anteksiler** [proteusthemes/one-click-demo-import#105]
I would like to actually access the data being imported inside "pt-ocdi/before_widgets_import" action.
What is the correct way of doing that?

**Comment by capuderg** [comment]
Hi @anteksiler,

which data would you like to access?

You can access all imported data with WordPress functions, since at the stage of `pt-ocdi/before_widgets_import` action hook, the content is already imported and ready in WP.

If you are looking for the Importer data (mapping IDs, ...) you can access it like so:

```
$ocdi                            = OneClickDemoImport::get_instance();
$content_import_data = $ocdi->importer->get_importer_data();
$content_import_data['mapping']; // mapped data
```

Take care!
