### ISSUE TITLE
WooCommerce product categories, tags and attributes not imported

### ISSUE THREAD

**Issue by transbetacism** [proteusthemes/one-click-demo-import#106]
Hi,

When I import the attached XML via the plugin, the WooCommerce product categories, tags and attributes are not imported. When I import the same file via the WordPress importer, then they are imported and assigned to the products.

[products-with-media_v1-1.xml.zip](https://github.com/proteusthemes/one-click-demo-import/files/973759/products-with-media_v1-1.xml.zip)

/Joakim

**Comment by capuderg** [comment]
Hi,

I've just tested my own WooCommerce import file and it imported categories, tags and attributes just ok. We also never had these issues with our themes, where we also use WooCommerce and categories and tags are always imported ok.

I've looked at your file and I see that there are no instances of:
- `<wp:term_taxonomy><![CDATA[pa_`, which indicate product attributes (`pa_`),
- `<wp:term_taxonomy><![CDATA[product_cat]]></wp:term_taxonomy>`, which indicate product categories,
- `<wp:term_taxonomy><![CDATA[product_tag]]></wp:term_taxonomy>`, which indicate product tags.

So the problem here is your export file.

Take care!

**Comment by transbetacism** [comment]
Thanks for looking into this! It seems the native WordPress importer is a bit more "forgiving", as categories, attributes and tags are imported automatically if any products are assigned to them.

But I have added the above taxonomies to my import file and it works now!
