### ISSUE TITLE
Sub pages not importing

### ISSUE THREAD

**Issue by mandava** [proteusthemes/one-click-demo-import#109]
I was trying to import a demo file with multiple subpages. OCDI imports just the parent page and then skips the rest of the pages from there. 

Log:

---Downloaded files---
The import files for: Beautiful were successfully downloaded!
Initial max execution time = 30
Files info:
Site URL = http://beautiful-pro.dev
Data file = /srv/www/beautiful-pro/wp-content/themes/beautiful-pro/xml/beautiful.xml
Widget file = /srv/www/beautiful-pro/wp-content/themes/beautiful-pro/xml/beautiful-widgets.wie
Customizer file = /srv/www/beautiful-pro/wp-content/themes/beautiful-pro/xml/beautiful-settings.dat
Redux files:
not defined!

---Importing widgets---
Welcome Message : 

Text - Welcome to my Website - Imported

---Importing customizer settings---
Customizer settings import finished!

Demo URL: http://demo.studiopress.com/beautiful/
Demo Content: [beautiful.xml.zip](https://github.com/proteusthemes/one-click-demo-import/files/1016548/beautiful.xml.zip)

**Comment by capuderg** [comment]
Hi,

that's strange, because I already tested importing parent-child-grandchild imports and they worked just ok for me.

I've also created a new XML import file with:
-parent
--child 1
---grandchild 1.1
---grandchild 1.2
--child 2

And it imported ok.

Your XML file does not even import the child pages, which is very strange. Please try to export a new file from your original site and don't modify the XML file in any way and try again.

Take care!

**Comment by mandava** [comment]
Thanks for the prompt response. I guess the issue is with the XML file itself. Will export a new file and try to import it.
