### ISSUE TITLE
Problem importing same image multiple times

### ISSUE THREAD

**Issue by anastis** [proteusthemes/one-click-demo-import#119]
We are distributing sample content for our themes. Its source are the demo sites themselves. Since many demo images have a restrictive license and cannot be redistributed, we pass the exported XML files through a custom script that replaces all image URLs to point to a specific sample image URL. The script replaces carefully all possible instances such as in `<wp:attachment_url>`, in `<guid isPermaLink="false">`, in json strings, as well as properly handling serialized values.

The only thing it won't replace is the `_wp_attachment_metadata` serialized arrays that hold each image's generated sizes and other metadata, e.g.
```a:5:{s:5:"width";i:1600;s:6:"height";i:750;s:4:"file";s:18:"2017/08/room01.jpg";s:5:"sizes";a:13:{s:9:"thumbnail";a:4:{s:4:"file";s:18:"room01-150x150.jpg";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:10:"image/jpeg";}```

Now, the default `wordpress-importer` plugin handles this just fine. It imports the same sample image multiple times (not ideal  but hey! it works!) and properly uses them wherever they are used, notably as featured images.

Unfortunately, OCDI won't behave similarly. The sample image is only imported once (which **could** be a good thing), but it doesn't get assigned as featured image on posts where it's used, resulting in an incomplete import.

The log file generated doesn't provide any helpful info to help investigate the issue. The only difference in the log between a vanilla XML and one processed by the script, is a few `New AJAX call!` that are present in the vanilla XML.

Let me know if I can provide any more info to debug this issue.

**Comment by capuderg** [comment]
Hi,

I don't see this as a real plugin issue, since your import process is unique and you are modifying the original WP export file...

Importing the same image multiple times does not sound ok to me and it's correct, that our content importer does not import it multiple times. We are using the new WP importer 2.0: https://github.com/humanmade/wordpress-importer, so some differences from the current WP importer are possible.

The way we solve the copyright image issue is to have a "duplicate" demo page, where we then blur the images and we export the content for our users from this duplicated demo page. This duplicate is also located on a different server, so when users are importing the content, they are not sending requests to the main demo page...

Take care!

**Comment by primozcigler** [comment]
I'd just like to add to the @capuderg's comment that we're working on a solution where you won't need to do anything like swapping the images anymore because the XML files will be prepared for you in the remote server (like he suggested already). We have proof of concept working alredy.

If you want to be notified when we release it, subscribe here: http://proteusthemes.github.io/one-click-demo-import/#ocdi-newsletter-signup

**Comment by anastis** [comment]
I guess I'll have to find a workaround until your proof of concept is actually released.
Thank you very much for your replies.

**Comment by wildrain** [comment]
Hi,

Do you find any solution for this "Problem importing same image multiple times". If i have 10 demos then it's difficult for me to create 10 extra demo server with dummy images.
