### ISSUE TITLE
Couldn't activate the plugin after installing.

### ISSUE THREAD

**Issue by foreverpinetree** [proteusthemes/one-click-demo-import#125]
When I installed the plugin and began to activate it, it just threw an error:
**Parse error: syntax error, unexpected T_STRING in /home3/public_html/themes/wp_test/wp-content/plugins/one-click-demo-import/one-click-demo-import.php on line 41** 

Any suggestions?

My hosting environment:
Apache | 2.2.34
-- | --
PHP | 5.4.24
MySQL | 5.6.32-78.1

**Comment by capuderg** [comment]
Hi,

did you download the plugin from here: https://wordpress.org/plugins/one-click-demo-import/ ?

Are you sure you are using PHP 5.4? This issue usually appears for PHP version 5.3 or lower, since it does not support namespaces...

Please try to update the PHP version to at least 5.6, but 7.0 or 7.1 is recommended.

Take care!

**Comment by foreverpinetree** [comment]
Hi,
Yes I downloaded the plugin from the WordPress offical site, and my PHP does is 5.4.24, I know that PHP  supports namespaces since 5.3, so I am very curious about this issue.
I installed it to my another hosting which runs PHP5.6 and it works fine.

Thank you. I close this issue.
