### ISSUE TITLE
Import completed but in reality not

### ISSUE THREAD

**Issue by DannyCork** [proteusthemes/one-click-demo-import#127]
Hi,
Firstly, nice work on this plugin!

When attempting to import demo data, I select the data I want to import and after a few seconds I see Import completed! Time for a beer ! 

Just upon opening the beer I noticed that the uploads folder doesn't contain any new data. Unfortunately the celebratory beer is now on hold :(

Upon close inspection I can see that there are multiple requests to admin-ajax.php which appear as 200 OK eg:
`https://xxxxx.com/wp-admin/admin-ajax.php?action=soodi_download_file&type=content&demo=1&_wpnonce=xxxxxxx`

However upon inspecting the browser's network console these responses are visible:
```
{
    "success": false,
    "data": "Could not write file /www/xxxx.com/wp-content/uploads/demo_files/demo-content.xml"
}
```

![screen shot 2017-12-06 at 01 43 15](https://user-images.githubusercontent.com/3512672/33640183-eecd299e-da26-11e7-9f72-d0be9fb0db5e.png)

The reason for the failure is a directory permission issue when attempting to write the downloaded data.Took me a while to figure this out, **might be worth adding a check, if success is false display the error.**

Thanks.

**Comment by capuderg** [comment]
Hi @DannyCork ,

are you sure, you are using our version of the plugin (and not a forked one or a totally different plugin)?

Why do I ask that? Because we do not write the content file to `.../wp-uploads/demo_files/...` and the AJAX action is not called "soodi_download_file".

We also display an error message, if the content files can't be downloaded...

Please verify, that you are using our plugin from here: https://wordpress.org/plugins/one-click-demo-import/ and let me know.

Take care!
