### ISSUE TITLE
Image missing from content.xml and demo import in loop!

### ISSUE THREAD

**Issue by bdthemes** [proteusthemes/one-click-demo-import#128]
Hi, At first thanks for develop this plugin.

When some how any image missing in content.xml demo import not finished anymore. it's just wait and check again and again it's just fall in loop maybe: http://prntscr.com/hoe4tp look here same things happen thousand times: https://pastebin.com/0FGHgGWJ and still continue...

is it not possible **if image not found just skip that and finish the import**?

**Comment by capuderg** [comment]
Hi,

if an image is missing (fails to import), the importer will try to import it on every new AJAX call and since the new AJAX calls are set to 25 seconds by default, this might make the importer stuck in a loop.

You could change the AJAX lengths to something bigger with out plugin filter, but do know, that some server have a limitation of 30 seconds for the "max_execution_time".

Or, a better solution, you could create a new content.xml file (make a new export file from your WordPress site), which would not include the missing images and so the import would not be stuck in the loop.

Take care!

**Comment by bdthemes** [comment]
Still same problem for some server with latest xml, some server did not import correctly. some times it's take 20-30 minutes to import that's so much boring. can you give me correct solution? or improve the import system and add skip missing image filter?

**Comment by capuderg** [comment]
Hi,

if your latest XML file doesn't have any missing images and the import still takes a lot of time, then it might also be a problem of your server (where the images are located). Or are you using very big images for your demo import (which would take a lot of time to download)?

We currently do not plan to add the functionality to skip missing images, but you are more than welcome to create a pull request and if everything works OK, we can merge it to the plugin.

Another option is to use the filter to disable the generation of smaller images. For that look at the [plugin FAQ section](https://wordpress.org/plugins/one-click-demo-import/) with the title "How to disable generation of smaller images (thumbnails) during the content import".

Take care!
