### ISSUE TITLE
Problem in category assignment in customizer panel

### ISSUE THREAD

**Issue by pzstar** [proteusthemes/one-click-demo-import#143]
I have implemented this plugin on one of my Free Theme Viral that is on wordpress.org. It is basically a magazine theme. I have implemented this plugin to import the demo. The demo import works perfectly on a fresh install but does not work with old ones. The categories are not assigned properly in the old site resulting in improper demo import. I tried to search on your forum and found out that you have done this for menu mapping in the widgets. It would be really a very good plugin to import demo in magazine themes if you guys can implement it in the category as well.

**Comment by capuderg** [comment]
Hi,

remapping menu IDs in menu widgets is easier then remapping category IDs in the content, different widgets and menu items.

As you already figured out, the problem is that with existing content, the imported categories get a different ID, but the new import uses the old IDs of these categories to assign theme in different content of the site.

If you want to solve this issue for a specific widget, then you can reuse the code, that fixes the menu widget imports.

The main point of this plugin is to import the demo data on fresh WP installation, so I don't really see this as a plugin issue. If you have existing content on your WP site, then you don't need the demo data. The demo data is just that, "demo data" ,and it will be changed to the users content anyway.
