### ISSUE TITLE
Preview image  one demo import

### ISSUE THREAD

**Issue by dhimanbarua** [proteusthemes/one-click-demo-import#150]
1. how can I show preview image when only one demo import is predefined.
2. How to change the location of the "Import Demo Data" plugin page in Appearance -> Import Demo Data? I want show WordPress admin panel? Import Demo Data

**Comment by capuderg** [comment]
Hi,

1. there is no option for showing a preview image, when only one demo import is predefined. There is "no need" for it, since the demo import should look like the one and only demo page.
2. look at the question/answer for "How to change the location, title and other parameters of the plugin page?" in the FAQ section of the plugin page: https://wordpress.org/plugins/one-click-demo-import/

Take care!
