### ISSUE TITLE
Update GUID

### ISSUE THREAD

**Issue by Profit87** [proteusthemes/one-click-demo-import#45]
After the data is not going to spoil the update URL in the column "guid".
Maybe that's why my function does not work (Get Attachment ID from URL)
``` php 
function get_attachment_id_from_src( $image_src ) {
	global $wpdb;
	$query = "SELECT ID FROM {$wpdb->posts} WHERE guid='$image_src'";
	$id = $wpdb->get_var( $query );
	return $id;
}
```
It is possible to fix?
Thank you.

**Comment by capuderg** [comment]
Hi,

Could you please explain in more details, when and what you want to achieve? I don't understand what the actual problem is...

If you want to force the image URL changes in the context import, then you can try this filter:

```
add_filter( 'pt-ocdi/importer_options', 'ocdi_importer_options' );
function ocdi_importer_options( $options ) {
  $options['aggressive_url_search'] = true;
}
```

Content importer note for `aggressive_url_search` option:

> bool $aggressive_url_search Should we search/replace for URLs aggressively? (True searches all posts' content for old URLs and replaces, false checks for `<img class="wp-image-*">` only. Default is false.)

Take care!
