### ISSUE TITLE
Class OCDI_Importer: set logger in constructor?

### ISSUE THREAD

**Issue by primozcigler** [proteusthemes/one-click-demo-import#8]
It will be a little bit cleaner if you allow option to set a Logger directly by passing it to the constructor function: https://github.com/proteusthemes/one-click-demo-import/blob/master/inc/class-ocdi-importer.php

You can still leave public method `set_logger` so it can still be changed or set after object initialization.

**Comment by capuderg** [comment]
Aha, so that we migrate the setting of the logger to the importer class in the importer constructor?

And we get rid of this line (we "move" it to the importer custructor): https://github.com/proteusthemes/one-click-demo-import/blob/master/one-click-demo-import.php#L406

The initialization of the OCDI_Logger stays in the `setup_plugin_with_filter_data`, right?

**Comment by primozcigler** [comment]
Yes.

**Comment by primozcigler** [comment]
I would set `$logger = null` in the argument and then check if it is actually set: 

```php
if ( ! empty( $logger ) ) {
  $this->set_logger( $logger );
}
```

**Comment by capuderg** [comment]
Now using the correct set_logger method: 15315f957f1a543f2943bf160ab65aeea37d91e3
