### ISSUE TITLE
Issue's with SVG's

### ISSUE THREAD

**Issue by mxaGianluca** [proteusthemes/one-click-demo-import#83]
It seems that the importer doesn't work if there's an SVG in the library. It gives an error "Failed to import ..svg (Media).

After this none of the pages / posts are imported. Once i remove the SVG from the XML export the import doesn't fail.

Don't know if it's intended but wanted you to know.

**Comment by primozcigler** [comment]
I think that this is the problem of the WP itself? Can you upload the .svg directly via media library?

**Comment by capuderg** [comment]
Hi,

yes, as @primozcigler said, this is a core WP issue, since SVG files are not allowed to be uploaded to WP. If you try to upload a svg file via the Media uploader, you get this error:

> This file type is not allowed. Please try another.

Anyway, this import error should not block importing of other pages and posts... Which version of our OCDI plugin are you using?

Take care!
